# Generated by Django 4.2.24 on 2025-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_for_desktop', models.FileField(upload_to='banners/desktop')),
                ('image_for_mobile', models.FileField(upload_to='banners/desktop')),
                ('status', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white')], default='black', max_length=10)),
            ],
        ),
    ]
