# Generated by Django 4.2.24 on 2025-10-15 06:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_productvariant_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', '250grms'), ('M', '500grms'), ('L', '1000grms')], max_length=5),
        ),
    ]
