# Generated by Django 4.2.24 on 2025-10-27 05:17

from django.db import migrations, models
import multiselectfield.db.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_info',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nutrition Information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', '500grms'), ('L', '1000grms')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
