# Generated by Django 4.2.24 on 2025-10-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_description_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
