# Generated by Django 4.2.24 on 2026-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('250grms', '250grms'), ('500grms', '500grms'), ('750grms', '750grms'), ('1kg', '1kg')], max_length=10),
        ),
    ]
