# Generated by Django 4.2.24 on 2026-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sizeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('250 grms', '250 grms'), ('500 grms', '500 grms'), ('750 grms', '750 grms'), ('1 kg', '1 kg')], max_length=10),
        ),
        migrations.DeleteModel(
            name='SizePrice',
        ),
    ]
